### PR TITLE
[Review] Request from 'schubi2' @ 'yast/yast-packager/review_160810_add_on_product_license'

### PR DESCRIPTION
**Pull request by schubi2**
I have tested the latest build together the latest SDK release.

Please review the following changes:
  * f1c7e9c Do not ask add-on product licences again after restarting YaST due self-update

### CODE REVIEW

**Comment by kobliha** [comment]
@schubi2 And what happens if the user actually `declined` the license? IMO it was not added, but then you will add it without asking...

**Comment by imobachgs** [comment]
Moreover we need to check if this method is used also when adding regular add-ons (not added using a `add_on_products.xml`) (I'm not sure about it).

**Comment by schubi2** [comment]
@kobliha 
"And what happens if the user actually declined the license? IMO it was not added, but then you will add it without asking..." I have tried: The user cannot continue without accepting this add-on license.

**Comment by schubi2** [comment]
I have tested some use cases documented here:
https://trello.com/c/h7DzsthA/647-2-sle-12-sp2-p1-992608-add-ons-added-via-add-on-products-xml-are-lost-after-self-update
@kobliha , @imobachgs have I missed some other use cases ?

**Comment by imobachgs** [comment]
I've found a scenario that won't work (note `<ask_user>` option):

```xml
<add_on_products>
  <product_items config:type="list">
    <product_item>
      <name>SUSE Linux Enterprise Software Development Kit 12</name>
      <url>cd:/?alias=SDK</url>
      <path>/</path>
      <priority config:type="integer">50</priority>
      <ask_user config:type="boolean">true</check_media>
    </product_item>
  </product_items></add_on_products>
```

The user will be asked twice whether to include the add-on or not.

**Comment by lslezak** [comment]
JFYI: we should not need this after moving the self update step earlier.

**Comment by schubi2** [comment]
It is obsolete.

**Pull request closed without merging**
