### PR TITLE
Set InitialPreference in yast2-packager.desktop

### PR DESCRIPTION
**Pull request by Vogtinator**
By setting InitialPreference to 10, yast takes precedence over other handlers,
like archivers or software centers.

### CODE REVIEW

**Comment by Vogtinator** [comment]
Ping?

**Comment by Vogtinator** [comment]
Ping?

If you don't accept PRs, just disable it. It might attract contributors otherwise.

**Comment by teclator** [comment]
@Vogtinator sorry for not reviewing it before. Of course we accept contributions, but some of them could pass unnoticed taking in account the number of repositories we have and maintain if a reviewer request is not set explicitly. 

And asking for review on #yast IRC channel at irc.opensuse.org (freenode) is also the quickest way to get attention.

**Comment by teclator** [comment]
@Vogtinator closing it by now. Feel free to reopen it if you plan to work on it.

**Pull request closed without merging**
