### PR TITLE
online repo popup: change wording to passive

### PR DESCRIPTION
**Pull request by lnussel**
Change wording of the popup that asks to enable online repos to
passive. Additionally move the actual question so it's at the end of
the dialog even in low memory situations.

### CODE REVIEW

**Comment by jreidinger** [comment]
@lnussel do you have permissions to merge or should we merge it for you? BTW changelog entry and version increase is missing here.

**Comment by lnussel** [comment]
I did half of the work already instead of complaining in a bug, could someone else handle the paperwork please? :) I don't know if I have permissions but I certainly don't want to interfere with your process. Just consider me as random dude from the internet :)

**Comment by teclator** [comment]
LGTM

**Comment by dgdavid** [comment]
| Before | After |
|--------|-------|
| low_memory_warning_before | low_memory_warning_after |

**Comment by dgdavid** [comment]
@teclator, @lnussel 

I added an [new commit](https://github.com/yast/yast-packager/pull/400/commits/938af6a10fe054255792306521df4f1edccc76f6) fixing the extra empty lines (see the [screenshots above](#issuecomment-458549323)) when the low memory warning is shown. Now it looks like the screenshot below:

low_memory_warning_after_modified


Is still the PR looking good for both of you?

Thank you!

**Comment by lnussel** [comment]
:+1:

**Pull request merged**
