### PR TITLE
Use options from partitioner during test mount (bcn#915758)

### PR DESCRIPTION
**Pull request by ancorgs**
This is a backport of the fix at version 3.1.43

### CODE REVIEW

**Comment by lslezak** [comment]
Just a note: For backports it's a good idea to mention the original commit or PR so we can easily compare the Ruby and the YCP version.

In this case it's PR #80.

**Comment by lslezak** [comment]
LGTM

**Comment by lslezak** [comment]
BTW, what about PR #81? It is also related to device mounting, maybe it should be backported too?

**Comment by ancorgs** [comment]
Ok, I will include more information about the backport and reuse this PR to also backport PR #81

**Pull request merged**
