### PR TITLE
fixed crash when editing the default URL of a new addon (bsc#937948)

### PR DESCRIPTION
**Pull request by lslezak**
- The problem is that `URI("ftp://")` raises `URI::InvalidURIError` exception. We have to fix the defaults. 
- Also improved handling of invalid URLs.
- 3.1.75

### CODE REVIEW

**Comment by jreidinger** [comment]
LGTM

**Comment by coolo** [comment]
https://openqa.suse.de/tests/102784/modules/addon_products_sle/steps/8

**Comment by kobliha** [comment]
Already reported as https://bugzilla.suse.com/show_bug.cgi?id=935082 and https://bugzilla.suse.com/show_bug.cgi?id=938786

**Comment by kobliha** [comment]
BTW, I'm wondering where do we have unit tests for this bugfix?

**Pull request merged**
