### PR TITLE
Fix layout of Add-On screen (bsc#951720)

### PR DESCRIPTION
**Pull request by cwh42**
The old Dialog:
addondialog-license_old

How I changed it:
addon-license-new

Compare with the installation greeter:
greeter

### CODE REVIEW

**Comment by jreidinger** [comment]
in general looks good. Do you also test ncurses UI if it still fits into minimal terminal? It is usally tricky part.

**Comment by cwh42** [comment]
It did not get bigger - I just changed the order.
addon-textmode

**Comment by jreidinger** [comment]
LGTM

**Comment by okurz** [comment]
interested in trying to keep openQA up to date and running with needle update? 
:-)

**Comment by cwh42** [comment]
Doesn't break openQA: 
https://yast-openqa.suse.cz/tests/315#step/addon_products_sle/1

**Comment by okurz** [comment]
great! thank you :-)

**Pull request merged**
